# Generated by Django 3.2.9 on 2022-12-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0002_auto_20221222_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='PhoneNumberUsers',
            field=models.CharField(max_length=45),
        ),
    ]
