# Generated by Django 3.2.9 on 2022-12-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0003_alter_users_phonenumberusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningsupplies',
            name='expirationCleaningSupplies',
        ),
        migrations.RemoveField(
            model_name='cleaningsupplies',
            name='typeCleaningSupplies',
        ),
        migrations.RemoveField(
            model_name='electronicsupplies',
            name='expirationElectronicSupplies',
        ),
        migrations.RemoveField(
            model_name='electronicsupplies',
            name='typeElectronicSupplies',
        ),
        migrations.RemoveField(
            model_name='foodsupplies',
            name='typeFoodSupplies',
        ),
        migrations.RemoveField(
            model_name='medicalsupplies',
            name='typeMedicalSupplies',
        ),
        migrations.RemoveField(
            model_name='users',
            name='PasswordUsers',
        ),
        migrations.RemoveField(
            model_name='users',
            name='PhoneNumberUsers',
        ),
        migrations.AddField(
            model_name='users',
            name='emailUsers',
            field=models.CharField(default=False, max_length=45),
        ),
        migrations.AddField(
            model_name='users',
            name='passwordUserss',
            field=models.CharField(default=False, max_length=45),
        ),
        migrations.AddField(
            model_name='users',
            name='phoneNumberUsers',
            field=models.CharField(default=False, max_length=45),
        ),
        migrations.AlterField(
            model_name='users',
            name='nameUsers',
            field=models.CharField(default=False, max_length=45),
        ),
        migrations.AlterField(
            model_name='users',
            name='surnameUsers',
            field=models.CharField(default=False, max_length=45),
        ),
    ]
